// Copyright 2025 Alby Hernández
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package api wires together all HTTP routes, middleware, and handlers.
package api

import (
	"io/fs"
	"log/slog"
	"net/http"

	"github.com/achetronic/memex/internal/api/handler"
	mw "github.com/achetronic/memex/internal/api/middleware"
	"github.com/achetronic/memex/internal/config"
	"github.com/achetronic/memex/internal/db"
	"github.com/achetronic/memex/internal/embedder"
	"github.com/achetronic/memex/internal/ingestion"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	// Side-effect import: registers swagger docs generated by swag init.
	_ "github.com/achetronic/memex/docs/api"
)

// RouterConfig carries all dependencies needed to build the HTTP router.
type RouterConfig struct {
	Store        *db.Store
	Embedder     *embedder.Embedder
	Worker       *ingestion.Worker
	Log          *slog.Logger
	Config       *config.Config
	MaxUploadMB  int64
	DefaultLimit int
	FrontendFS   fs.FS
}

// NewRouter creates and returns the fully configured chi router.
// It registers all API routes and the Swagger UI under /api/v1,
// and serves the embedded Vue frontend from the root.
func NewRouter(cfg RouterConfig) http.Handler {
	r := chi.NewRouter()

	// Global middleware.
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(mw.Recovery(cfg.Log))
	r.Use(mw.Logger(cfg.Log))

	// API v1.
	r.Route("/api/v1", func(r chi.Router) {
		// Swagger UI — no auth required.
		r.Get("/swagger/*", httpSwagger.WrapHandler)

		// GET /info — key-only auth (no namespace header required).
		r.Group(func(r chi.Router) {
			r.Use(mw.AuthKeyOnly(cfg.Config, cfg.Log))
			r.Get("/info", handler.NewInfo(cfg.Config, cfg.Log).Get)
		})

		// All other endpoints — full auth (key + namespace).
		r.Group(func(r chi.Router) {
			r.Use(mw.Auth(cfg.Config, cfg.Log))

			docs := handler.NewDocuments(cfg.Store, cfg.Worker, cfg.Log, cfg.MaxUploadMB)
			r.Post("/documents", docs.Upload)
			r.Get("/documents", docs.List)
			r.Get("/documents/{id}", docs.Get)
			r.Delete("/documents/{id}", docs.Delete)

			srch := handler.NewSearch(cfg.Store, cfg.Embedder, cfg.Log, cfg.DefaultLimit)
			r.Post("/search", srch.Query)

			health := handler.NewHealth(cfg.Store, cfg.Embedder, cfg.Log)
			r.Get("/health", health.Check)
		})
	})

	// Frontend: serve embedded Vue dist/ from root.
	// Requests not matching /api/v1 fall through to the SPA.
	r.Handle("/*", http.FileServer(http.FS(cfg.FrontendFS)))

	return r
}
